server:
  port: 8088

spring:
  application:
    name: spring-transaction
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: xiaojiebin
    url: jdbc:mysql://localhost:3306/cloud?serverTimezone=Asia/Shanghai