server:
  port: 8088


spring:
  application:
    name: spring-transaction
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: xiaojiebin
    url: jdbc:mysql://localhost:3306/cloud?serverTimezone=Asia/Shanghai

    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 3000000
      max-evictable-idle-time-millis: 4000000
      validation-query: SELECT 1 FROM DUAL
      filters: log4j2
      filter:
        stat:
          log-slow-sql: true
          db-type: mysql
          slow-sql-millis: 2000
        slf4j:
          enabled: true
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
logging:
  level:
    root: debug
